from .estimation_age import AgeEstimator
from .classification_multilabel import ClassificationEngine
from .basic_segmentation import BasicSegmentationEngine
from .binary_regression import BinaryRegressionEngine
